"use client";

import React, { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { RefreshCw, Sparkles } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { AnalyticsTiles } from "@/components/AnalyticsTiles";
import { BriefingCard } from "@/components/BriefingCard";
import { api, ApiError } from "@/lib/api";
import type { Dashboard } from "@/lib/types";

export default function DashboardPage() {
  const router = useRouter();
  const [data, setData] = useState<Dashboard | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      setData(await api.dashboard());
    } catch (err) {
      if (err instanceof ApiError && err.status === 401) router.replace("/login");
      else setError("Could not load your dashboard.");
    } finally {
      setLoading(false);
    }
  }, [router]);

  useEffect(() => {
    load();
  }, [load]);

  async function generate() {
    setGenerating(true);
    setError(null);
    try {
      await api.generateBriefing();
      // Dev runs the build inline; poll once after a short beat for the broker path.
      await new Promise((r) => setTimeout(r, 800));
      await load();
    } catch {
      setError("Could not generate a briefing.");
    } finally {
      setGenerating(false);
    }
  }

  const briefing = data?.briefing ?? null;
  const items = briefing?.items ?? [];

  return (
    <AppShell>
      <header className="mb-6 flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight text-slate-100">
            Intelligence Dashboard
          </h1>
          <p className="mt-1 text-sm text-slate-500">
            {briefing
              ? briefing.summary ?? "Your ranked, highest-value actions."
              : "Your ranked, highest-value actions — generated by the Strategic Council."}
          </p>
        </div>
        <button onClick={generate} disabled={generating} className="btn-primary">
          {generating ? (
            <RefreshCw className="h-4 w-4 animate-spin" />
          ) : (
            <Sparkles className="h-4 w-4" />
          )}
          {generating ? "Generating…" : "Generate briefing"}
        </button>
      </header>

      {data && (
        <div className="mb-6">
          <AnalyticsTiles analytics={data.analytics} />
        </div>
      )}

      {error && (
        <p className="mb-4 rounded-xl border border-signal-red/30 bg-signal-red/10 px-4 py-3 text-sm text-signal-red">
          {error}
        </p>
      )}

      {loading ? (
        <div className="space-y-3">
          {[0, 1, 2].map((i) => (
            <div key={i} className="card h-32 animate-pulse" />
          ))}
        </div>
      ) : items.length > 0 ? (
        <div className="space-y-4">
          {items.map((it) => (
            <BriefingCard key={it.id} item={it} />
          ))}
        </div>
      ) : (
        <div className="card flex flex-col items-center justify-center px-6 py-16 text-center">
          <div className="mb-4 grid h-12 w-12 place-items-center rounded-2xl bg-accent/10 text-accent-soft">
            <Sparkles className="h-6 w-6" />
          </div>
          <h3 className="text-base font-semibold text-slate-200">No briefing yet</h3>
          <p className="mt-1 max-w-sm text-sm text-slate-500">
            Generate your first briefing and the Strategic Council will surface the highest-value
            actions from the latest signals.
          </p>
          <button onClick={generate} disabled={generating} className="btn-primary mt-5">
            <Sparkles className="h-4 w-4" />
            Generate my first briefing
          </button>
        </div>
      )}
    </AppShell>
  );
}
